# Dados de conexao com o banco H2
spring:
  datasource:
    url: jdbc:h2:mem:test
    password:
  # Configuracao do cliente web do banco H2
  h2:
    console:
      enabled: true
  # Configuracao para mostrar o SQL no console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  jwt:
    secret: "u7F!k9zP2sQw4eR8tYxC1vB3nM5aL6dJ"
    prefix: "Bearer "
    expire:
      days: 0
      hours: 0
      minutes: 30