# Dados de conexao com o banco H2
spring:
  datasource:
    url: jdbc:h2:mem:test
    password:
  # Configuracao do cliente web do banco H2
  h2:
    console:
      enabled: true
  # Configuracao para mostrar o SQL no console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true